### PR TITLE
Add Chatbot

### LINKED ISSUE #111: [FEATURE] Simple Website chatbot
### Detailed description

When clicking on the chatbot logo 
A window will be open 
example: 
image

---

As in the above image we can see, two options got displayed.
- when a user clicks on a particular option, a specific answer should be displayed over there.

Example:
Option 1: Hello
user clicks on it and got a response: Hello 

Open 2: I need help
after clicking on it, got a response: Hello, how we can help you?

Open 3: Need resources for learning:>
response: Here is your free resources list link. 

### Context

This will be very helpful for everyone

### Possible implementation

If you have any doubts or questions, let us know below

Thanks.

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abdullmustyy**
## Fixes Issue
Closes #111 

## Changes proposed
- Add website Chatbot.

## Screenshots

https://user-images.githubusercontent.com/87391935/197006508-71c5329a-29c3-4582-bf00-219ec3b54b6a.mp4

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Great 😄, We really loved it

Thanks for contributing to this project.

If you want to contribute more to open-source then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Comment by abdullmustyy** [comment]
> Great 😄, We really loved it
> 
> Thanks for contributing to this project.
> 
> If you want to contribute more to open-source then must check out other open-source projects and communities:
> 
> * [Thecyberworld](https://github.com/thecyberworld).
> * [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
> * [kabir0x23](https://github.com/kabir0x23)

☺️☺️☺️
But, it's not showing on the website. @kabir0x23

**Comment by kabir0x23** [comment]
> 
> ☺️☺️☺️ But, it's not showing on the website. @kabir0x23

image

**Comment by kabir0x23** [comment]
> > ☺️☺️☺️ But, it's not showing on the website. @kabir0x23
> 
> image

fixing this , will be resolved in some minutes

**Comment by abdullmustyy** [comment]
> > ☺️☺️☺️ But, it's not showing on the website. @kabir0x23
> 
> image

Idg, was there an issue please?

**Comment by abdullmustyy** [comment]
I mean it's not showing on thecyberhub.org

**Comment by abdullmustyy** [comment]
> I mean it's not showing on thecyberhub.org



> > > ☺️☺️☺️ But, it's not showing on the website. @kabir0x23
> > 
> > 
> > image
> 
> fixing this , will be resolved in some minutes

Ohh, okay. 
Thank you.

**Comment by kabir0x23** [comment]
> > > ☺️☺️☺️ But, it's not showing on the website. @kabir0x23
> > 
> > 
> > image
> 
> Idg, was there an issue please?

issue was in build and deploy

fixed now

**Comment by abdullmustyy** [comment]
> > > > ☺️☺️☺️ But, it's not showing on the website. @kabir0x23
> > > 
> > > 
> > > image
> > 
> > 
> > Idg, was there an issue please?
> 
> issue was in build and deploy
> 
> fixed now

Yayyy.

**Comment by abdullmustyy** [comment]
Wait. 
Is it just me or the website is now blank? 
Screenshot_20221021-061401_Chrome

**Comment by kabir0x23** [comment]
> Wait. Is it just me or the website is now blank? Screenshot_20221021-061401_Chrome

yes some kind of errors

**Comment by abdullmustyy** [comment]
> > Wait. Is it just I or the website is now blank? Screenshot_20221021-061401_Chrome
> 
> yes some kind of errors

Aww. Hope it's not serious.

**Comment by kabir0x23** [comment]
firebase transfer data got exhausted.

like background video or some logo were comming from cloud storages

fixed for now.

**Comment by kabir0x23** [comment]
got the issue: was coming from the bot:
image

**Comment by abdullmustyy** [comment]
> got the issue: was coming from the bot: image

😓😓😓
Is there anything I need to do?

**Comment by kabir0x23** [comment]
> 😓😓😓 Is there anything I need to do?

this was working fine on local, but on a website, don't know why it is not working

will give a look on weekend then it will be available on the website

**Comment by abdullmustyy** [comment]
> > 😓😓😓 Is there anything I need to do?
> 
> this was working fine on local, but on a website, don't know why it is not working
> 
> will give a look on weekend then it will be available on the website

Alright. 
Thank you.

**Pull request merged**
