### PR TITLE
fix: Updating Blog is not working

### LINKED ISSUE #330: [BUG] Updating Blog is not working (branch: dev)
### Describe the bug

Update Blog is not working (branch: dev)

frontend: [https://github.com/thecyberworld/thecyberhub.org](https://github.com/thecyberworld/thecyberhub.org)

backend: [https://github.com/thecyberworld/api.thecyberhub.org](https://github.com/thecyberworld/api.thecyberhub.org)

### To Reproduce

Update Blog is not working (branch: dev)
dashboard > blogs > + button you w ill get the form

error is comming in 
in blog slice:
under updateBlog
const state = thunkAPI.getState();
getstate is undefined

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ryan-byte**
## Fixes Issue

Closes #330 

## Changes proposed

Capture
-FIX: the server is using the "PUT" method instead of "PATCH" in update blog route.

Capture2
Capture1
-These changes fixes thunkAPI being undefined.

### **Changes made in CTF.jsx > line 11 NEEDS TO BE CHECKED  (it was a temporary fix because the frontend was not working)**

**Bugs Found (related to update blog):**

- [x]  **Reloading update blog page bug (frontend issue):** dashboard > blogs > + button > reload the page.
- [x]  **Tags updates to empty if left unchanged (frontend issue):** when tags is left unchanged the front will send tags as an empty array which makes the server update it to empty.
- [x]  **Pressing cancel on update blog page raises an error**

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Fix Bugs related to update blog 

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ryan-byte** [comment]
fixed: Reloading update blog page bug (frontend issue): dashboard > blogs > + button > reload the page.

Capture

It seems like the front was trying to access variables inside searchedBlog when it was undefined (basically undefined.something raised an error).
searchedBlog will take `{tags: []}` instead of `{}` because of this at line 99 ( `searchedBlog.tags.join(", ")`).

**Comment by ryan-byte** [comment]
Capture

It seems like when the tags is updated the blogData.tags takes the updated value, but when it is not updated then blogData.tags will be an empty array and `[] || ["SomeOldTag"]` would give `[]`.

**Comment by ryan-byte** [comment]
**fix: pressing cancel on update blog page raises an error.**

**Make sure to check the CTF.jsx file the changes that i have made are in line 11, i only changed it because i got an import error.**

**Comment by kabir0x23** [comment]
> Done fixing Bugs related to update blog page, Hope this helps.
> 
> **Make sure to check the CTF.jsx file the changes that i have made are in line 11, i only changed it because I got an import error.**

Nice, those are correct, i just merged those changes and forgot to fix the import in certificate 
Thanks

**Review by kabir0x23 — COMMENTED** [review]
Thank you for submitting a pull request for issue #330 . We will review and merge it as soon as possible. If you encounter any other issues, please create a new issue so that the open source community can address it. In the meantime, you can check out other [issues](https://github.com/thecyberworld/thecyberhub.org/issues) 

Your contribution is greatly appreciated and we hope to see more from you in the future. Thank you again for your support.

**Review by kabir0x23 — APPROVED** [review]
Awesome.
Thank you for submitting this pull request for issue #330 . After reviewing the changes, I am happy to approve and accept this pull request. Your contribution is greatly appreciated and will help to improve the project for everyone. Thank you for your support and for taking the time to make this contribution. We hope to see more from you in the future.

**Pull request merged**
