### PR TITLE
Sidebar Fixed

### PR DESCRIPTION
**Pull request by sanketshevare**
## Fixes Issue
fix: #290 

## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
Hey @sanketshevare , thanks for creating pr on issue no. #290 

The closing drop is working

Selecting a nested list, won't close the sidebar itself


https://user-images.githubusercontent.com/44284877/205850345-e1b751d6-2fda-4083-a85c-193e3549ed2f.mp4

When we click on the nested item,  it should close the whole sidebar, example set to the previous state

**Comment by kabir0x23** [comment]
> Hey @sanketshevare , thanks for creating pr on issue no. #290
> 
> The closing drop is working
> 
> Selecting a nested list, won't close the sidebar itself
> 
> When we click on the nested item, it should close the whole sidebar, example set to the previous state

you also can restructure the sidebar

**Comment by sanketshevare** [comment]
https://user-images.githubusercontent.com/69853783/205859605-bb2ae085-bb75-4ac8-a181-3c48fc630255.mp4

Like this?

**Review by kabir0x23 — COMMENTED** [review]
Awesome

**Review by kabir0x23 — APPROVED** [review]
Amazing 

Thanks for contirbuting in open-source project.

**Pull request merged**
