### PR TITLE
Add Community Page

### PR DESCRIPTION
**Pull request by abdullmustyy**
## Changes proposed
- Add Community Page.

## Screenshots

Screenshot (9)

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — COMMENTED** [review]
image

Downgrading this package on purpose?

**Comment by abdullmustyy** [comment]
> image
> 
> Downgrading this package on purpose?

No, all I did was npm install.

**Comment by kabir0x23** [comment]
> > image
> > Downgrading this package on purpose?
> 
> No, all I did was npm install.

okayy..

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks to contributing to this project.

Don't forget to check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
