### PR TITLE
Add Quiz Categories

### LINKED ISSUE #102: [FEATURE] Quiz section: Add categories
### Detailed description

We have a simple quiz section:
image

so we want to improve it.

### Context

Here is an example:
image

we have to mention
networking, security awareness etx
more examples:
image

### Possible implementation

after completing the above task we can move further.

### Additional information

if you have any questions or doubts, feel free to ask below. 👇

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abdullmustyy**
closes #102 

## Changes proposed

- Add quiz categories section.
- Display quiz questions based on the category chosen.

## Screenshots

Categories

https://user-images.githubusercontent.com/87391935/193873278-f501f727-a413-41f5-af5a-f7656a4725b7.mp4

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Awesome

Thanks for contributing to this open-soruce project.

**Comment by abdullmustyy** [comment]
> Awesome
> 
> Thanks for contributing to this open-source project.

Thank you.

I'll go through the open issues and check for one I'd love to hop on.

**Comment by kabir0x23** [comment]
> > Awesome
> > Thanks for contributing to this open-source project.
> 
> Thank you.
> 
> I'll go through the open issues and check for one I'd love to hop on.

Great, I am on creating new issues, will let you know.

Thank you😀

**Comment by abdullmustyy** [comment]
> > > Awesome
> > > Thanks for contributing to this open-source project.
> > 
> > 
> > Thank you.
> > I'll go through the open issues and check for one I'd love to hop on.
> 
> Great, I am on creating new issues, will let you know.
> 
> Thank you😀

Alright. 
Sorry to bother you @kabir0x23 

This is my first time participating in hacktoberfest and I have a question. 
- How do I know if this counts as hacktoberfest PR?

**Comment by kabir0x23** [comment]
> > > > Awesome
> > > > Thanks for contributing to this open-source project.
> > > 
> > > 
> > > Thank you.
> > > I'll go through the open issues and check for one I'd love to hop on.
> > 
> > 
> > Great, I am on creating new issues, will let you know.
> > Thank you😀
> 
> Alright. Sorry to bother you @kabir0x23
> 
> This is my first time participating in hacktoberfest and I have a question.
> 
>     * How do I know if this counts as hacktoberfest PR?

Hey, there is no need to be sorry to ask anything. 
we are here to help. 😀

Here is the link, it will be accepted after 7 days.
https://hacktoberfest.com/profile/
image

**Comment by abdullmustyy** [comment]
> > > > > Awesome
> > > > > Thanks for contributing to this open-source project.
> > > > 
> > > > 
> > > > Thank you.
> > > > I'll go through the open issues and check for one I'd love to hop on.
> > > 
> > > 
> > > Great, I am on creating new issues, will let you know.
> > > Thank you😀
> > 
> > 
> > Alright. Sorry to bother you @kabir0x23
> > This is my first time participating in hacktoberfest and I have a question.
> > ```
> > * How do I know if this counts as hacktoberfest PR?
> > ```
> 
> Hey, there is no need to be sorry to ask anything. we are here to help. 😀
> 
> Here is the link, it will be accepted after 7 days. https://hacktoberfest.com/profile/ image

Alright, thank you so much.

**Pull request merged**
