### PR TITLE
Add new registration page

### LINKED ISSUE #112: [FEATURE] Registration from page
### Detailed description

Registration from the page:
We have to build a similar page like this using react + css or styled-components.
left section got completed, right form section got left.
image

### Context

Registration from page will help while registring for accounts or for events.

### Possible implementation

_No response_

### Additional information

If you have any questions, let us know below

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iyinolu**
## Fixes Issue

Closes #112 

## Changes proposed

- New registration page.
- Hide header and footer on registration page

## Screenshots
Screenshot 2022-10-21 at 11 56 54 AM

## Note to reviewers

None

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Hey @iyinolu 

we are using react-icons can youu replace existing icons witht the react-icons

here is the link: https://react-icons.github.io/react-icons/search

**Comment by iyinolu** [comment]
Ok, I will do that. @kabir0x23

**Comment by iyinolu** [comment]
@kabir0x23 how do you I get more details on the failed check?

**Review by kabir0x23 — APPROVED** [review]
Great 😄

Thanks for contributing to this project.

If you want to contribute more to open-source then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
