### PR TITLE
Added big nav-bar on hover

### LINKED ISSUE #223: [FEATURE] New navbar design, big navbar
### Detailed description

We have to create a big navbar onhover

image

### Context

_no_response_

### Possible implementation

_No response_

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Bzsmrf**
Closes #223  

## FEATURE
New navbar design, big navbar on hover 

## Screenshots

image

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
We have to make like this:
- you can remove prep item from the navber:
image

**Comment by kabir0x23** [comment]
If you have any questions or doubts, you can ask

**Comment by Bzsmrf** [comment]
Sir i was in a exam will soon get back to the issue

**Comment by kabir0x23** [comment]
> Sir i was in a exam will soon get back to the issue 

No worries, I will manage my self 😄

**Review by kabir0x23 — APPROVED** [review]
Great 😄

Thanks for contributing to this project.

If you want to contribute more to open-source then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
