### PR TITLE
Add static submit page Closes #180

### LINKED ISSUE #180: [FEATURE] Build a simple static submission page
### Detailed description

Build a simple static page submission page under Play CTF.

### Context

The value stored in the backend: is 193471289037
If a user submits the value 193471289037, turn the button green. and display congrats.

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tanyaa-arora**
Closes #180 
image
 Add a submit page according to the guidelines given to solve the issue.

### CODE REVIEW

**Comment by tanyaa-arora** [comment]
Hey, could you check the PR?

**Review by kabir0x23 — COMMENTED** [review]
Hey @tanyaa-arora , as you can see, we are using core css only.
would you like to convert the tailwind code into css?

Thank you.

**Comment by tanyaa-arora** [comment]
Sure, I'll do that.

**Comment by tanyaa-arora** [comment]
I made the changes in my branch, but I don't know how I closed the request and whether the changes are even implemented or not. Can you guide me on how to update the changes from my branch and create a PR

**Comment by kabir0x23** [comment]
once you send the PR
and when you change on the same branch and push those changes again, those will be going to reflect on your PR as well.

if you made a new branch with new code:
- go to the forked repo
- change to the new branch
- and there will be the option of contributing to the Project if your branch is containing some changes

**Comment by kabir0x23** [comment]
You already have made the PR, Awesome

**Comment by tanyaa-arora** [comment]
yes, thankyou for guiding me through the issue

**Pull request closed without merging**
