### PR TITLE
Add Jobs/internship page

### LINKED ISSUE #108: [FEATURE] Jobs/Internships page
### Detailed description

For example, what we trying to build:

drawing

our website link: 
https://www.thecyberhub.org/prep/jobs
http://localhost:3000/prep/jobs

### Context

The jobs page will going to help community members and other users 

### Possible implementation

tech-stack: react and styled-components or CSS

### Additional information

If you need any help or have any doubts, let us know.

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abdullmustyy**
closes #108 

## Changes proposed

- Add Jobs/internship page

## Screenshots

[New Recording - 10_16_2022, 5_16_23 AM.webm](https://user-images.githubusercontent.com/87391935/196030168-a0005e45-00b8-4ea7-9c97-f448aff8eb15.webm)

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — COMMENTED** [review]
Awesome, You have done an amazing work

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Comment by abdullmustyy** [comment]
> Awesome, You have done an amazing work

Thank you so much. 
It was a pleasure working on it.

**Comment by kabir0x23** [comment]
> > Awesome, You have done an amazing work
> 
> Thank you so much. It was a pleasure working on it.

Thanks for working on this
You have done an amazing work
🚀

**Comment by kabir0x23** [comment]
> > Awesome, You have done an amazing work
> 
> Thank you so much. It was a pleasure working on it.

here is another issue if you like to work on#197 

there is another even going on, just have to submit a simple project and get swag, intrested, its solo participating?

**Comment by abdullmustyy** [comment]
> > > Awesome, You have done an amazing work
> > 
> > 
> > Thank you so much. It was a pleasure working on it.
> 
> Thanks for working on this You have done an amazing work 🚀

☺️☺️☺️

Screenshot_20221016-174517_Chrome

I think there is a typo, you meant right now yeah?

**Comment by abdullmustyy** [comment]
> > > Awesome, You have done an amazing work
> > 
> > 
> > Thank you so much. It was a pleasure working on it.
> 
> here is another issue if you like to work on #197
> 
> there is another even going on, just have to submit a simple project and get swag, interested, its solo participating?

Thank you @kabir0x23 
I'll check it out, and yes I'm interested. 😁

**Comment by kabir0x23** [comment]
> I think there is a typo, you meant "right now" yeah?

Now do one thing.

fetch and pull the latest data in your forked repo.
create a new branch from that forked repo, and then you can fix that repo

**Comment by abdullmustyy** [comment]
> > I think there is a typo, you meant "right now" yeah?
> 
> Now do one thing.
> 
> fetch and pull the latest data in your forked repo. create a new branch from that forked repo, and then you can fix that repo

I already did something before seeing this.
I deleted my fork of the repo on GitHub, and on my local system.
Created a new fork, so everything is fresh now. I hope that won't cause any problems.

**Comment by kabir0x23** [comment]
> > > I think there is a typo, you meant "right now" yeah?
> > 
> > 
> > Now do one thing.
> > fetch and pull the latest data in your forked repo. create a new branch from that forked repo, and then you can fix that repo
> 
> I already did something before seeing this. I deleted my fork of the repo on GitHub, and on my local system. Created a new fork, so everything is fresh now. I hope that won't cause any problems.

yes nice 💪🏽

**Comment by kabir0x23** [comment]
And some suggestions:
1. when ever you are working on issues, when pr got ready, use issue number in the pr, so it will close that issue automatically when pr got merged.
- exmaples are, closes #196 , fix fixes close

**Comment by kabir0x23** [comment]
You are doing amaing work, keep it up 🔥

**Pull request merged**
