### PR TITLE
Fix row cards & improvement in home screen of quiz categories

### LINKED ISSUE #496: [FEATURE] improvement in home screen of quiz categories
### Detailed description

When we visit the quiz section, we are presented with categories or topics to choose from for taking the quiz, and once selected, we can begin the quiz.
 
Screenshot 2023-10-11 at 1 49 17 PM

### Context

 I propose restructuring the categories section into a card section that will facilitate easy selection of quiz topics and enhance user-friendliness

### Possible implementation

This will make it easier for users to select quiz topics and improve the overall user experience.

Screenshot 2023-10-11 at 1 53 12 PM

After the successfully changing in categories section our topic will be looks like roadmap card.

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0xlarmideh**
## Fixes Issue

Closes #512
Closes #496

## Screenshots

Screenshot 2023-10-23 133351
image

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
hey

thanks for contributions 

but the issue is here, 

example when we click on card, it should open in the new route

example, if someone even open that url it should open specific quiz/

quiz > click on security
URL/quiz/security and it;s content should be displayed there

if u need any help let me know 

thank you,

**Comment by 0xlarmideh** [comment]
@kabir0x23 This issue wasn't mentioned on the issue description I worked on.

**Comment by kabir0x23** [comment]
> @kabir0x23 This issue wasn't mentioned on the issue description I worked on.

yah, i think i have discussed with him on different pull req, then he created this issue and he was working on that issue...

**Comment by 0xlarmideh** [comment]
I will check this today.

**Comment by 0xlarmideh** [comment]
@kabir0x23 I don't it's a good idea to route to different paths when a category is clicked.

**Comment by kabir0x23** [comment]
> @kabir0x23 I don't it's a good idea to route to different paths when a category is clicked.

we are going to add more fields with search option later, so it is necessary as of now

**Pull request closed without merging**
