### PR TITLE
Updated Navbars with the Desptop version

### LINKED ISSUE #274: [BUG] Sidebar dropwown not working
### Describe the bug

 The sidebar dropdown not working
image
when we click on this nav-item nothing happens

### To Reproduce

Click on the Sidebar > learn. dropdown not working

### Expected Behavior

Like this: the drop should be displayed 
image

_No response_

### Screenshot/ Video

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Rahul-Palamarthi**
fix #274 
 updated the code so that they can be selected in desktop version

### CODE REVIEW

**Review by Rahul-Palamarthi — COMMENTED** [review]
Looks good

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
Hey

Only left with small issue:
Once the dropdown got opend, it won't closed automatically after clicking on item

Example 1: hover on the navitem learn: once the dropdown got opend , we have to click om the navitem learn to close the dropdown. 
Even we click on the dropdown item, it should close the dropdown, but it is stll opened

**Comment by Rahul-Palamarthi** [comment]
Yes actually I tried to close it but the close function is a child and we can't pass function to the parent in react so it is not possible to close

Even if we declare the close function in the parent also there will be a single state occupied by both the **learn** and **Resources** element and it will give a bug

**Comment by Rahul-Palamarthi** [comment]
But I will try to figure the issue along with other issues in future

**Comment by kabir0x23** [comment]
> Yes actually I tried to close it but the close function is a child and we can't pass function to the parent in react so it is not possible to close
> 
> Even if we declare the close function in the parent also there will be a single state occupied by both the **learn** and **Resources** element and it will give a bug

Okay, we will fix that issue.

**Pull request merged**
