### PR TITLE
feat [#189]: redesign quiz section

### LINKED ISSUE #189: [FEATURE] Design Improvement of Quiz Section
### Detailed description

Design Improvement of Quiz Section

### Context

image

### Possible implementation

_No response_

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jahtomini**
Closes #189 

## Changes proposed

- redesign quiz section
- abbreviate labels of `<CategoriesButtons />` 
- fix uneven width between buttons and the quiz body
- add reusable utility component to render the progress indicator across categories in a new `utils/components` directory

## Screen~~shots~~ recording

https://user-images.githubusercontent.com/93228906/198066172-04510467-545b-460e-844f-d32434d5627e.mp4

## Note to reviewers
There seems to be a lot of repetition in the `src/components/Resources/Quiz/Categories/` components. I didn't dig deep or bother refactoring cause I didn't want to go out of scope but maybe I could open a separate issue on it?

## Code of Conduct

- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Great 😄

Thanks for contributing to this project.

If you want to contribute more to open-source then must check out other open-source projects and communities:

- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Comment by kabir0x23** [comment]
> There seems to be a lot of repetition in the src/components/Resources/Quiz/Categories/ components. I didn't dig deep or bother refactoring cause I didn't want to go out of scope but maybe I could open a separate issue on it?

yes, there is a lot of repetition, and could be done in a simpler way, 
If you want to work on this issue, You can create an issue, and I will assign that issue to you

Thank you.

**Comment by kabir0x23** [comment]
@jahtomini

**Comment by jahtomini** [comment]
> > There seems to be a lot of repetition in the src/components/Resources/Quiz/Categories/ components. I didn't dig deep or bother refactoring cause I didn't want to go out of scope but maybe I could open a separate issue on it?
> 
> yes, there is a lot of repetition, and could be done in a simpler way, If you want to work on this issue, You can create an issue, and I will assign that issue to you
> 
> Thank you.

Great, will do

**Pull request merged**
