### PR TITLE
Add button link to Open-Source page

### PR DESCRIPTION
**Pull request by abdullmustyy**
## Changes proposed

- Add a button link in the landing page community section.
- This button navigates to the Open-Source projects page.

## Screenshots

[New Recording - 10_14_2022, 9_25_21 PM.webm](https://user-images.githubusercontent.com/87391935/195937763-cd12b1ac-e002-4893-8874-2539859bca9d.webm)

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
I think you have included a jobs page too.

**Comment by kabir0x23** [comment]
Want to give a suggestions 

when ever you are working on different issues?

always create new branches from the main branch

this branch is containing everything you are changing.
image

**Comment by abdullmustyy** [comment]
> Want to give a suggestions
> 
> when ever you are working on different issues?
> 
> always create new branches from the main branch
> 
> this branch is containing everything you are changing. image

Alright, I've noted that. Thank you. 
Is there anything I need to do?

**Comment by kabir0x23** [comment]
See, you pr containing these things,
image

store these data, somewhere else

go to your forked repo
fetch the data.
create a new branch, do changes, and send the pr here.
then go to you forked branch, fetch data, and create new branch, work on that and send that pr

everytime you going to create new branches, previous changes that you have made, are not going to be there, until we merge that, so no need to worry about that.

**Comment by abdullmustyy** [comment]
> See, you pr containing these things, image
> 
> store these data, somewhere else
> 
> go to your forked repo to fetch the data. create a new branch, do changes, and send the pr here. then go to you forked branch, fetch data, and create new branch, work on that and send that pr
> 
> everytime you going to create new branches, previous changes that you have made, are not going to be there, until we merge that, so no need to worry about that.

This is quite confusing @kabir0x23 

Even for the Job/Internship page, I'm working on, I created a branch from the main but it still has these commits too. 

I'll try to do what you asked though. Thank you.

**Comment by kabir0x23** [comment]
First fetch the new data: 
image
 yourbrach is too old now

!st you was working on jobs page.
Then i think, you created a new branch from the job branch instead of the main branch
so all of the jobs data came along with that branch

**Comment by kabir0x23** [comment]
let me fix the code.

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Comment by abdullmustyy** [comment]
> let me fix the code.

Thank you very much @kabir0x23 

Before I make a PR from the jobs branch, I'll make sure it doesn't have these issues.

**Comment by kabir0x23** [comment]
> Thank you very much @kabir0x23
> 
> Before I make a PR from the jobs branch, I'll make sure it doesn't have these issues.

If you face any issues, let me know 😄

**Pull request merged**
