### PR TITLE
Fix blog entry overflow on mobile

### LINKED ISSUE #142: [BUG] Overflowing the blogs (not responsive)
### Describe the bug

Overflowing the blogs section:
- not responsive in blogs 

Blogs section:
- overflowing the sides in the blog section:
- image

Event section:
- working fine in events (similar design and code)
- image

### To Reproduce

Website: https://www.thecyberhub.org/events
Localhost: http://localhost:3000/blogs

### Expected Behavior

_No response_

### Screenshot/ Video

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by indiehjaerta**
## Fixes Issue

Closes #142

## Changes proposed

Updates the blog entry container to a max-width of 400px to a max-width of 400px to make sure it doesn't try to take up 400px on smaller screens. Also updated the image width and height to 100% and auto to make the image fit the container in width and still look good with height auto

## Screenshots

image

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Awesome

Looks nice

Thanks for the contribution

**Comment by kabir0x23** [comment]
@indiehjaerta i have a question are you on devsquad? (same as hacktober fest, just in team)
we need just need a 1 team member

**Comment by indiehjaerta** [comment]
No I've never heard of it, whats their page?

**Comment by kabir0x23** [comment]
> No I've never heard of it, what's their page?

https://www.hacksquad.dev/friend/a2FiaXJqMjMxMEBnbWFpbC5jb20=

once you joined let me know will share a invite link

**Comment by indiehjaerta** [comment]
> > No I've never heard of it, what's their page?
> 
> https://www.hacksquad.dev/friend/a2FiaXJqMjMxMEBnbWFpbC5jb20=
> 
> once you joined let me know will share a invite link

I've joined but I see you got a lot of PRs already and I don't know if I'm able to contribute that much.

**Comment by kabir0x23** [comment]
> I've joined but I see you got a lot of PRs already and I don't know if I'm able to contribute that much.
Don't matter
Here is the invite link: https://www.hacksquad.dev/invite/cl97czwzx0007jq09ilzouhoh
we just have to be in top60 to get swags, (with valid prs)

**Comment by kabir0x23** [comment]
If we do more pull request , can come under top3

If you need good projects to contribute, you can checkout my profile

**Comment by kabir0x23** [comment]
@indiehjaerta hey
Can you join this squad? https://www.hacksquad.dev/invite/cl98u719k000gme09fnrqpzoo
we are also going to lead on top in this sqaud soon

my friend wanting to join our team and and there is no seat left
please can you join our another team? https://www.hacksquad.dev/invite/cl98u719k000gme09fnrqpzoo
first you have to leave and join thanks

**Comment by indiehjaerta** [comment]
> @indiehjaerta hey Can you join this squad? https://www.hacksquad.dev/invite/cl98u719k000gme09fnrqpzoo we are also going to lead on top in this sqaud soon
> 
> my friend wanting to join our team and and there is no seat left please can you join our another team? https://www.hacksquad.dev/invite/cl98u719k000gme09fnrqpzoo first you have to leave and join thanks

think you have to kick me i see no leave button

**Comment by kabir0x23** [comment]
> think you have to kick me I see no leave button

okay, no issues, keep contributing to open-source 😄

**Pull request merged**
