### PR TITLE
add dropdown navbar

### LINKED ISSUE #101: [FEATURE] Dropdown navbar
### Detailed description

Nav bar
We have this type of navbar

If you click on any Item, it will smooth scroll down.
image

for each each sub-sections, we have different navbars
so it becomes complex to use for new users.

If you will have any confusion, disscuss beflow: 👇

### Context

So we are looking for an on-hover and on-clicked drop-down navbar.
like: image

but when we click the top nav item it should smooth scroll down, as it is working now

example resources nav-item:
so on-hover and on-clicked on resources navbar
image

it should display it's below content:
image

and after 
on-hover and on-clicked on prep navbar-item
these items should be displayed
image

If we have on the resources section
only we have to add on hove dropdown.

With this.
- User experience will be good
- Easy to use

### Possible implementation

This type of navbar is easy for navigation.
image

### Additional information

If you have any questions or doubts feel free to discuss them below.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
## Fixes Issue

closes #101 

## Changes proposed

Added a dropdown navbar, didn't replace it everywhere, the sample can be seen on the homepage.

## Note to reviewers

sorry that the code I added isn't professional. I can raise another issue and work on it. 
This pr is just to confirm whether I am on right track on not.

## Code of Conduct
- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Amazing

Thanks for contributing to Thecyberworld.

**Comment by kabir0x23** [comment]
one suggestion
- can you do one more thing?
- The sidebar is still the same. so instead of hovering we can use onclick dropdown other

**Comment by kabir0x23** [comment]
@saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
Sure. I'll try @kabir0x23

**Comment by saimaheshtaduri** [comment]
@kabir0x23 check it out now.

**Comment by kabir0x23** [comment]
> @kabir0x23 check it out now.

amazing work
image

there are small conflicts will you resolve them?
Thanks

**Comment by kabir0x23** [comment]
let me know if you need any help
once you solved this small confilcts 
I will merge this pr

**Comment by kabir0x23** [comment]
@saimaheshtaduri 
I have a new issue, will create it.

---
At homepage:
image

when we click on community, it will go down by smooth scroll

We want to use the same navbar on every page

so when we are on a different page, how we can accomplish that
image
if we click on community, can we go back and smooth-scroll to the community section?

If not, i will change the structure then.

**Pull request merged**
