### PR TITLE
feat: blog page #99

### LINKED ISSUE #99: [FEATURE] Blogs page
### Detailed description

Add a Blog section to the site
Can be made using React + styled-components.
- Add dummy data after completing this page, we will add backend later on.
### Context

Blogs plays important role in learning

### Possible implementation

Example: 👇
- You can make this type UI under the blog section.
- https://www.thecyberhub.org/resources/blogs

image

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aritroCoder**
## Fixes Issue 99

closes #99 

## Changes proposed
Added a blog page

## Screenshots
Screenshot from 2022-09-29 22-59-45

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — COMMENTED** [review]
You have to do Two things now:

- do not include .gitignore and package-lock.json files in your commits 
- and do not delete those file 
- just copy the same file from our project and paste those into your file and push the code.

then i will be able to merge this pull request.

Thanks.

**Comment by mohakgupt** [comment]
image
How is this layout?

**Comment by aritroCoder** [comment]
done

**Review by kabir0x23 — APPROVED** [review]
Code looks good to me ✔

Thanks for the your contribution.

**Comment by kabir0x23** [comment]
@aritroCoder 
like if we click on blog, then the particular blog will open
click on blog 1 -> contents of blog 1 will open'
click on blog 2 -> contents of blog 2 will open

will you able to do that
that's a new issue

or will i assign this to another one?

**Comment by aritroCoder** [comment]
> @aritroCoder like if we click on blog, then the particular blog will open click on blog 1 -> contents of blog 1 will open' click on blog 2 -> contents of blog 2 will open
> 
> will you able to do that that's a new issue
> 
> or will i assign this to another one?

I will work on it
Create a seperate issue and please assign me

**Comment by kabir0x23** [comment]
> > @aritroCoder like if we click on blog, then the particular blog will open click on blog 1 -> contents of blog 1 will open' click on blog 2 -> contents of blog 2 will open
> > will you able to do that that's a new issue
> > or will i assign this to another one?
> 
> I will work on it Create a seperate issue and please assign me

Awesome
I am doing this in 10 minutes, just adjusting the website, and adding some data.

**Comment by kabir0x23** [comment]
comment on this issue, and i will assign it to you
https://github.com/thecyberworld/thecyberhub.org/issues/116

**Pull request merged**
