### PR TITLE
fix: navbar design and typos

### LINKED ISSUE #103: [Bug] Not Responsive on Smaller Screens
### Describe the bug

1. A part of navbar is collapsing on smaller screens. 
2.  And there is overflow on x-axis on smaller screens.

### To Reproduce

1. Open the Website
2. Change the resolution of the window to smaller sizes.
3. Scroll left to right to see the defect.

### Expected Behavior

Shouldn't be no overflow at x-axis and navbar elements shouldn't collapse with one-another on smaller sizes

### Screenshot/ Video

Right side hamburger menu half-appearing.
Screenshot (24)

"Community" and "Join Us" collapsing and Website title at left.
Screenshot (25)

x-axis overflow
Screenshot (26)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sumitbishti**
Closes #103 

## Fixes Issue
1. Responsive Design Bugs at Navbar and Footer
2. Fixed typo at folder level

### CODE REVIEW

**Review by kabir0x23 — COMMENTED** [review]
Good work @sumitbishti 
- one thing should be done before merging.
- you have to remove the package-lock.json file from your commit 
- do not deleted the file

If you have any doubts and need any type of help let us know.

Thanks.

**Comment by sumitbishti** [comment]
> Good work @sumitbishti
> 
> * one thing should be done before merging.
> * you have to remove the package-lock.json file from your commit
> * do not deleted the file
> 
> If you have any doubts and need any type of help let us know.
> 
> Thanks.

How should i proceed?

**Comment by kabir0x23** [comment]
> It's done, please review.

As I said, don't delete the file
image
Don't have to delete the file, you can revert the file.
or you can visit our repo and copy code from the file and paste it in your file

If you need any help and having doubts, let me know

**Comment by kabir0x23** [comment]
image

and don't include these file in your code

**Comment by sumitbishti** [comment]
> > It's done, please review.
> 
> As I said, don't delete the file image Don't have to delete the file, you can revert the file. or you can visit our repo and copy code from the file and paste it in your file
> 
> If you need any help and having doubts, let me know

I didn't delete the file. I just didn't inculded it in this commit. I have the file locally.

**Comment by kabir0x23** [comment]
> > > It's done, please review.
> > 
> > 
> > As I said, don't delete the file image Don't have to delete the file, you can revert the file. or you can visit our repo and copy code from the file and paste it in your file
> > If you need any help and having doubts, let me know
> 
> I didn't delete the file. I just didn't inculded it in this commit. I have the file locally.

remove that file from .gitignore

**Comment by sumitbishti** [comment]
> image
> 
> and don't include these file in your code

By "these files" do you mean .gitignore file? Because package-lock.json file isn't there.
If it is what you meant then i would like to know why?

**Comment by kabir0x23** [comment]
> > image
> > and don't include these file in your code
> 
> By "these files" do you mean .gitignore file? Because package-lock.json file isn't there. If it is what you meant then i would like to know why?

image

You have included package-lock.json file in your .gitignore file, see above
just remove and push the code again

**Comment by sumitbishti** [comment]
> > > image
> > > and don't include these file in your code
> > 
> > 
> > By "these files" do you mean .gitignore file? Because package-lock.json file isn't there. If it is what you meant then i would like to know why?
> 
> image
> 
> You have included package-lock.json file in your .gitignore file, see above just remove and push the code again

But then package-lock.json file will also get pushed! Do tou want that?

**Comment by kabir0x23** [comment]
See  we have already mentioned about this
https://github.com/thecyberworld/thecyberhub.org/blob/main/CONTRIBUTING.md

image

**Comment by sumitbishti** [comment]
> See we have already mentioned about this https://github.com/thecyberworld/thecyberhub.org/blob/main/CONTRIBUTING.md
> 
> image

Since i have commited the said files, what should i do now?

**Comment by kabir0x23** [comment]
Do one thing
copy gitignore and package-lock.json from my repository 
and paste the same to the same on your files
then just push the code. it will automatically be reflected here,

**Comment by sumitbishti** [comment]
> Do one thing copy gitignore and package-lock.json from my repository and paste the same to the same on your files then just push the code. it will automatically be reflected here,

It's done.

**Comment by kabir0x23** [comment]
> > Do one thing copy gitignore and package-lock.json from my repository and paste the same to the same on your files then just push the code. it will automatically be reflected here,
> 
> It's done.

now here are 4 files
image


> > Do one thing copy gitignore and package-lock.json from my repository and paste the same to the same on your files then just push the code. it will automatically be reflected here,
> 
> It's done.

now there are four files
image

**Comment by kabir0x23** [comment]
> > > Do one thing copy gitignore and package-lock.json from my repository and paste the same to the same on your files then just push the code. it will automatically be reflected here,
> > 
> > 
> > It's done.
> 
> now here are 4 files image

You are doing:
- first, you do changes to the files
- then you are uploaded into your forked branch
- that's why those 4 files are getting changed
- then you are creating a pull request from that forked branch

--- 

do 

first forked the branch
then clone it
add upstrearm origin url(our repo address)
create branch 
do changes 
then pull the code direct in our branch not yours

or use github desktop

**Comment by sumitbishti** [comment]
> > > > Do one thing copy gitignore and package-lock.json from my repository and paste the same to the same on your files then just push the code. it will automatically be reflected here,
> > > 
> > > 
> > > It's done.
> > 
> > 
> > now here are 4 files image
> 
> You are doing:
> 
> * first, you do changes to the files
> * then you are uploaded into your forked branch
> * that's why those 4 files are getting changed
> * then you are creating a pull request from that forked branch
> 
> do
> 
> first forked the branch then clone it add upstrearm origin url(our repo address) create branch do changes then pull the code direct in our branch not yours
> 
> or use github desktop

I don't understand what are you trying to achieve here?
I have some questions for you.

1. If i first fork your branch and then clone it, then in my understanding, the changes will automatically go to my forked repo first, not yours original repo. And then from there i will open a PR. I don't think i  can directly push the changes to your repo if i fork your repo first, instead of cloning it directly.
2. I have already done the first five steps you mentioned above correctly, but i don't understand the last step.
3. Should i open a new PR, doing all the changes from the start?

**Review by kabir0x23 — APPROVED** [review]
Awesome

Everything is fine now

Thanks for the contributions 


one tip (mostly every one doing this but):
- never do, 
  - git add *
  - git add .
- if you do this will add everything in the commit.
- so we have to amanually add using git add file_name 

Thanks

**Comment by sumitbishti** [comment]
> Awesome
> 
> Everything is fine now
> 
> Thanks for the contributions
> 
> one tip (mostly every one doing this but):
> 
> * never do,
>   
>   * git add *
>   * git add .
> * if you do this will add everything in the commit.
> * so we have to amanually add using git add file_name
> 
> Thanks

Thanks for the advice, I'll keep that in mind👍🏻

**Pull request merged**
